version: "3.10"
services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MAIN_DATABASE: ${MAIN_DATABASE}
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api_container
    env_file:
      - ./.env
    build: ./api
    ports:
      - 8000:8000

volumes:
  mongodb_data_container:
